const expertise = [
  {key:'rto',icon:'🚚',title:'RTO & Vehicle Compliance',text:'Registration, permits, fitness, tax, transfer, NOC, Vahan 4.0 and statutory fleet control.',color:'#0b69b7'},
  {key:'insurance',icon:'🛡️',title:'Insurance & Claims',text:'Motor, CPM, package, third-party, survey, documentation, settlement and policy renewal control.',color:'#18a56b'},
  {key:'purchase',icon:'🛒',title:'Purchase & Vendor Control',text:'PR, RFQ, comparison, negotiation, PO, delivery follow-up, billing coordination and vendor performance.',color:'#f7bd43'},
  {key:'management',icon:'👔',title:'Operations Control Management',text:'Department coordination, KPI reviews, aging control, escalation, decisions and action closure.',color:'#7457d8'},
  {key:'maintenance',icon:'⚙️',title:'Mechanical Maintenance',text:'Preventive, predictive and breakdown maintenance with MTBF, MTTR, uptime and cost control.',color:'#e55252'},
  {key:'mis',icon:'📊',title:'MIS & Dashboards',text:'Daily, weekly and monthly reports, Power BI, Excel and management analytics.',color:'#0b69b7'},
  {key:'data',icon:'🗄️',title:'Data Control & Governance',text:'Master data, validation, reconciliation, audit trail, role access and single source of truth.',color:'#18a56b'},
  {key:'erp',icon:'🧩',title:'ERP Workflow Control',text:'PR, PO, GRN, GIN, billing, inventory, maintenance, hire and approvals.',color:'#f7bd43'},
  {key:'sap',icon:'🔷',title:'SAP S/4HANA PM & ETM',text:'Equipment master, notifications, orders, plans, cost posting, deployment and utilization.',color:'#7457d8'},
  {key:'store',icon:'🏪',title:'Store & Spare Control',text:'GRN, issue, returns, stock levels, ABC/FSN, critical spares and reconciliation.',color:'#0b69b7'},
  {key:'finance',icon:'💰',title:'Finance MIS & Cost Control',text:'Budget, actual, commitment, forecast, cash flow, vendor billing and profitability.',color:'#18a56b'},
  {key:'breakdown',icon:'🔧',title:'Breakdown Management',text:'Multi-site breakdown workflow, repair cost, spare control, warranty and aging reports.',color:'#e55252'},
  {key:'civil',icon:'🏗️',title:'Civil Operations Control',text:'Site requirements, subcontract work, measurement, material coordination, progress, billing and closure.',color:'#0b69b7'},
  {key:'automation',icon:'💻',title:'Software Automation',text:'Self-developed HTML, Apps Script, Google Sheets, VBA, API and mobile reporting systems.',color:'#7457d8'}
];
const projects = [
  {key:'road',icon:'🛣️',title:'Road Projects – PQC, DBM, BC, WMM & GSB',text:'Production, layer progress, plant output, material, fuel, quality and equipment MIS.'},
  {key:'railway',icon:'🚆',title:'Railway Projects',text:'Earthwork, bridges, station works, equipment deployment, milestones and constraints.'},
  {key:'building',icon:'🏢',title:'Building Projects',text:'RCC, finishing, MEP, material reconciliation, plant, manpower and subcontract monitoring.'},
  {key:'epc',icon:'🏗️',title:'EPC Projects',text:'Engineering, procurement, construction, commissioning, cost, schedule and change control.'},
  {key:'multisite',icon:'🌐',title:'Multi-Site Central MIS',text:'Site-wise login, standardized data, automatic consolidation and one management report.'},
  {key:'fuel',icon:'⛽',title:'Fuel & Fleet Automation',text:'Receipt, issue, stock, HMR/KMR, KM/L, L/Hr and abnormal consumption alerts.'}
];
const details = {

  purchase:{title:'Purchase, Procurement & Vendor Control',body:`<h3>Purchase Control Responsibilities</h3><ul><li>Convert site requirements into complete purchase requisitions with specifications, quantity, delivery location and required date.</li><li>Coordinate RFQ, technical and commercial comparison, negotiation, approval and purchase order release.</li><li>Track advance, manufacturing, inspection, dispatch, transport, delivery, GRN and vendor bill status.</li><li>Monitor pending indents, open POs, delayed supplies, rate variance, warranty terms and vendor performance.</li><li>Coordinate purchase, stores, finance, project and mechanical teams through one aging and escalation dashboard.</li></ul><div class="flow"><div>Requirement</div><div>PR / Indent</div><div>RFQ & Comparison</div><div>PO & Follow-up</div><div>GRN / Billing</div></div>`},
  civil:{title:'Civil Operations & Site Control',body:`<h3>Civil Operations Controls</h3><ul><li>Coordinate civil work requirements for camps, plants, foundations, sheds, workshops, utilities and project support facilities.</li><li>Track drawings, quantity, subcontractor scope, material requirement, manpower, machinery and execution schedule.</li><li>Monitor measurement sheets, work completion, quality observations, hindrances, RA bill support and final closure.</li><li>Link civil progress with purchase, stores, finance, mechanical installation and commissioning requirements.</li><li>Prepare site-wise progress, cost, pending decision and responsibility dashboards for management review.</li></ul>`},
  rto:{title:'RTO & Vehicle Compliance Management',body:`<h3>Scope of Work</h3><ul><li>New vehicle registration, temporary/permanent registration, RC correction and duplicate RC.</li><li>State and national permits, road tax, fitness certificates, PUC, NOC and ownership transfer.</li><li>Vahan 4.0 online processing, challan monitoring and document expiry tracking.</li><li>Project-wise vehicle document register with advance alerts for renewals.</li><li>Coordination with RTO agents, dealers, banks, insurers and site teams.</li></ul><div class="flow"><div>Vehicle Master</div><div>Document Check</div><div>Renewal Alert</div><div>RTO Submission</div><div>Compliance Closure</div></div>`},
  insurance:{title:'Insurance Portfolio & Claim Management',body:`<h3>Insurance Operations</h3><ul><li>Own Damage, Package, Third Party, CPM, commercial and private vehicle policies.</li><li>Policy renewal calendar, premium comparison, IDV, add-ons and insurer coordination.</li><li>Accident intimation, surveyor appointment, estimate, photographs, FIR/panchnama and claim file.</li><li>Workshop repair follow-up, salvage, depreciation, excess and settlement reconciliation.</li><li>Claim aging, pending documents, recovery status and management reporting.</li></ul>`},
  management:{title:'Operations & Department Management',body:`<h3>Management Responsibilities</h3><ul><li>Coordinate projects, site teams, purchase, stores, finance, planning, mechanical and management.</li><li>Define targets, responsibilities, review frequency, escalation matrix and closure dates.</li><li>Prepare executive dashboards, action trackers, risk registers and decision notes.</li><li>Monitor productivity, cost, quality, safety, utilization and project milestones.</li><li>Support MD/GM with accurate, timely and decision-ready information.</li></ul>`},
  maintenance:{title:'Mechanical Maintenance & Fleet Reliability',body:`<h3>Maintenance Controls</h3><ul><li>Preventive schedules based on calendar, HMR/KMR and OEM recommendations.</li><li>Breakdown notification, root cause analysis, repair approval, job card and closure.</li><li>MTBF, MTTR, uptime, downtime, repeat failure and cost per hour/km analysis.</li><li>AMC, warranty, service history, critical spares and vendor performance control.</li><li>Fleet coverage: crushers, batching/asphalt plants, pavers, rollers, excavators, cranes, tippers and workshop equipment.</li></ul>`},
  mis:{title:'Project MIS & Management Dashboards',body:`<h3>MIS Reporting</h3><ul><li>Daily, weekly and monthly project performance reports.</li><li>Power BI, Advanced Excel, Google Sheets and Looker Studio dashboards.</li><li>Production, utilization, fuel, breakdown, cost, budget, billing and cash-flow analytics.</li><li>Drill-down by project, site, machine, vendor, department, date and cost code.</li><li>Automated management packs with exception highlights and corrective actions.</li></ul>`},
  data:{title:'Data Control, Validation & Governance',body:`<h3>Data Framework</h3><ul><li>Master data for projects, sites, machines, vendors, employees, materials, cost codes and users.</li><li>Duplicate prevention, mandatory fields, dropdowns, format controls and maker-checker approval.</li><li>ERP versus Excel/Google Sheet reconciliation and missing transaction checks.</li><li>Role-based access, audit trail, backups, version control and data health checks.</li><li>Centralized single source of truth for management reporting.</li></ul>`},
  erp:{title:'ERP Operations & Workflow Control',body:`<h3>Integrated Processes</h3><ul><li>Purchase requisition, RFQ, comparison, PO, GRN, GIN, issue and vendor bill status.</li><li>Equipment master, work orders, breakdowns, preventive maintenance and service history.</li><li>Hire machinery agreements, deployment, log sheets, billing and vendor reconciliation.</li><li>Project, cost center, department and user-wise permissions and approvals.</li><li>As-Is/To-Be documentation, testing, training, implementation and issue resolution.</li></ul>`},
  sap:{title:'SAP S/4HANA PM & ETM',body:`<h3>SAP Functional Exposure</h3><ul><li>Equipment and functional location masters, maintenance plans, notifications and orders.</li><li>Preventive maintenance scheduling, confirmations, cost posting and settlement.</li><li>ETM deployment, internal/external hire, utilization, log sheets and billing support.</li><li>Material reservation, issue and purchase integration with maintenance orders.</li><li>Business process mapping, UAT, master migration and end-user support.</li></ul>`},
  store:{title:'Store, Inventory & Spare Parts Automation',body:`<h3>Store Controls</h3><ul><li>Receipt, inspection, GRN, bin location, issue, return, transfer and consumption.</li><li>Machine-wise spare consumption linked to job cards and work orders.</li><li>Minimum/maximum/reorder levels, ABC/FSN, slow/non-moving and critical stock.</li><li>ERP stock reconciliation, negative stock prevention, serial/batch tracking and audit trail.</li><li>Automatic low-stock alerts and purchase-indent generation.</li></ul>`},
  finance:{title:'Finance MIS, Budget and Project P&L',body:`<h3>Financial Controls</h3><ul><li>Monthly and annual OPEX/CAPEX budgets by project, department, machine and cost code.</li><li>Budget versus actual versus commitment versus forecast with variance analysis.</li><li>Revenue, certified billing, unbilled revenue, direct cost, overhead and margin.</li><li>Cash flow, vendor liability, collection, cost-to-complete, EAC and ETC.</li><li>Project profitability ranking, break-even and forecast-at-completion margin.</li></ul>`},
  breakdown:{title:'Breakdown, Repair Cost & Spare Control',body:`<h3>Breakdown Workflow</h3><ul><li>Record machine, reason, date/time, indent, site action, HO assignment, PO and closure.</li><li>Track priority, downtime, root cause, technician/vendor and repeat failures.</li><li>Capture labour, spare, transport, outside repair and total breakdown cost.</li><li>Control warranty claims, replaced part returns, scrap and supplier recovery.</li><li>Generate MTBF/MTTR, aging, Pareto and top-cost-machine dashboards.</li></ul>`},
  automation:{title:'Self-Developed Software & API Automation',body:`<h3>Applications and Technologies</h3><ul><li>Breakdown Management, Diesel Issue/Receipt, Daily Work Entry and Project MIS systems.</li><li>Mobile-responsive HTML/CSS/JavaScript frontends with Google Apps Script backend.</li><li>Google Sheets database, role-based login, PDF/Excel downloads and photo uploads.</li><li>Excel VBA for WhatsApp messaging, document attachment and repetitive reporting.</li><li>REST-style APIs, doGet/doPost, webhooks, tokens, logging and secure server-side API keys.</li></ul>`},
  road:{title:'Road Projects – PQC, DBM, BC, WMM & GSB',body:`<h3>Road Project MIS</h3><ul><li>PQC batching, paver output, concrete quality, dowel/tie bar and layer progress.</li><li>DBM/BC asphalt production, bitumen, temperature, paver and roller deployment.</li><li>WMM/GSB/crusher production, aggregate balance, lead, loading and transport.</li><li>Equipment utilization for crushers, RMC/asphalt plants, graders, excavators and tippers.</li><li>Daily target versus achievement, cost per MT/cum/km, downtime and material reconciliation.</li></ul>`},
  railway:{title:'Railway Project Operations',body:`<h3>Railway Coverage</h3><ul><li>Earthwork, bridges, track works, station/building works and equipment reporting.</li><li>Crusher, batching plant, excavator, crane, piling rig, dumper and track equipment utilization.</li><li>Traffic/block constraints, inspections, approvals, logistics and milestones.</li><li>Project cost, fuel, breakdown, spare and maintenance dashboards.</li><li>Multi-location consolidation for head-office review.</li></ul>`},
  building:{title:'Building Project Operations',body:`<h3>Building Project Controls</h3><ul><li>RCC, finishing, MEP, material, manpower, plant and subcontractor monitoring.</li><li>Concrete, steel, cement and shuttering reconciliation.</li><li>Tower crane, hoist, batching plant maintenance and utilization.</li><li>RA bill support, cost codes, budget variance and profitability.</li><li>Daily site reports, constraints and milestone dashboards.</li></ul>`},
  epc:{title:'EPC Project Management Reporting',body:`<h3>EPC Controls</h3><ul><li>Engineering deliverables, procurement, manufacturing/dispatch, construction and commissioning.</li><li>Long-lead items, vendor documents, inspection, logistics and site readiness.</li><li>Schedule versus actual, milestone delays, risk and recovery plans.</li><li>Committed cost, actual cost, cash flow, billing, collection and change orders.</li><li>Integrated engineering-procurement-construction-cost dashboard.</li></ul>`},
  multisite:{title:'Multiple Sites Merged into One Report',body:`<h3>Central MIS Architecture</h3><ul><li>Site-wise secure login and assigned-project data entry.</li><li>Standard templates and common masters across all projects.</li><li>Automatic consolidation into one head-office report without copy-paste.</li><li>Filters for project, site, machine, department, date, category and status.</li><li>Project-wise and consolidated PDF/Excel downloads.</li></ul>`},
  fuel:{title:'Fuel Receipt, Issue, Stock & Consumption Control',body:`<h3>Fuel Management</h3><ul><li>Receipt by supplier, bill, tank, project and date.</li><li>Machine-wise issue with code, HMR/KMR, quantity, operator and remarks.</li><li>Opening + receipt – issue = closing stock with physical reconciliation.</li><li>KM/L and L/Hr analysis, idling, abnormal use and leakage alerts.</li><li>Daily/monthly project-wise fuel cost and variance dashboards.</li></ul>`}
};
function renderCards(){
  document.getElementById('expertiseGrid').innerHTML=expertise.map((x,i)=>`<article class="expertise-card reveal delay-${i%4}" style="--accent:${x.color}" data-key="${x.key}"><div class="icon">${x.icon}</div><h3>${x.title}</h3><p>${x.text}</p><span class="open">Click for details →</span></article>`).join('');
  document.getElementById('projectGrid').innerHTML=projects.map((x,i)=>`<article class="project-card reveal delay-${i%3}" data-key="${x.key}"><div class="icon">${x.icon}</div><h3>${x.title}</h3><p>${x.text}</p><b>Open project details →</b></article>`).join('');
}
function openModal(key){const item=details[key];if(!item)return;document.getElementById('modalTitle').textContent=item.title;document.getElementById('modalBody').innerHTML=item.body;document.getElementById('detailModal').classList.add('active');document.body.style.overflow='hidden'}
function closeModal(){document.getElementById('detailModal').classList.remove('active');document.body.style.overflow=''}
function initReveal(){const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>io.observe(el))}
function animateCounters(){const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(!e.isIntersecting)return;const el=e.target,target=Number(el.dataset.counter);let start=0;const step=Math.max(1,Math.ceil(target/45));const timer=setInterval(()=>{start+=step;if(start>=target){start=target;clearInterval(timer)}el.textContent=start+(target===15?'+':target===35||target===95?'%':'')},28);io.unobserve(el)}),{threshold:.5});document.querySelectorAll('[data-counter]').forEach(el=>io.observe(el))}
async function downloadPDF(){const el=document.getElementById('resume');const opt={margin:[6,6,6,6],filename:'Manoj_Kumar_Vishwakarma_Operations_Control_Manager_CV.pdf',image:{type:'jpeg',quality:.98},html2canvas:{scale:2,useCORS:true,letterRendering:true},jsPDF:{unit:'mm',format:'a4',orientation:'portrait'},pagebreak:{mode:['css','legacy'],avoid:['.timeline-card','.info-panel','.expertise-card']}};await html2pdf().set(opt).from(el).save()}
function init(){renderCards();initReveal();animateCounters();setTimeout(()=>document.getElementById('pageLoader').classList.add('hidden'),550);
 document.addEventListener('click',e=>{const card=e.target.closest('[data-key]');if(card)openModal(card.dataset.key);const action=e.target.closest('[data-action]')?.dataset.action;if(action==='close-modal')closeModal();if(action==='print')window.print();if(action==='pdf')downloadPDF()});
 document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
 const nav=document.getElementById('navMenu');document.getElementById('menuToggle').onclick=()=>nav.classList.toggle('open');nav.querySelectorAll('a').forEach(a=>a.onclick=()=>nav.classList.remove('open'));
 const top=document.getElementById('backToTop');top.onclick=()=>scrollTo({top:0,behavior:'smooth'});window.addEventListener('scroll',()=>{const max=document.documentElement.scrollHeight-innerHeight;document.getElementById('scrollProgress').style.width=(scrollY/max*100)+'%';top.classList.toggle('show',scrollY>500)});
}
document.addEventListener('DOMContentLoaded',init);
